grafana:
  persistence:
    enabled: true
  rbac:
    pspEnabled: false
    namespaced: true
  ingress:
    enabled: true
    hosts: 
      - grafana-test-protools.dev.insee.io
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      micrometer:
        gnetId: 4701
        revision: 9
        datasource: Prometheus
  datasources:
    datasources.yaml:
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://my-prometheus-protools-server
