fr.insee.sndil.starter.role.administrateur=AdministrateurRP_ERA
##SWAGGER
#Client par defaut propose dans la popup de login
springdoc.swagger-ui.oauth.clientId=localhost-frontend

#Non lue par le programme java
fr.insee.sndil.starter.auth.url=https://auth.insee.test/auth
fr.insee.sndil.starter.springdoc.issuer-url-authorization=${fr.insee.sndil.starter.auth.url}/realms/agents-insee-interne/protocol/openid-connect/auth
fr.insee.sndil.starter.springdoc.issuer-url-refresh=${fr.insee.sndil.starter.auth.url}/realms/agents-insee-interne/protocol/openid-connect/token
fr.insee.sndil.starter.springdoc.issuer-url-token=${fr.insee.sndil.starter.auth.url}/realms/agents-insee-interne/protocol/openid-connect/token
fr.insee.sndil.starter.springdoc.issuer-description=Keycloak
fr.insee.sndil.starter.springdoc.contact-name=Le nom de votre contact
fr.insee.sndil.starter.springdoc.contact-email=un-email-fonctionnel@insee.fr
fr.insee.sndil.starter.springdoc.contact-url=https://www.insee.fr/fr/accueil

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${fr.insee.sndil.starter.auth.url}/realms/agents-insee-interne/protocol/openid-connect/certs