spring.config.import=optional:file:${HOME}/protools/local.properties

#--------------------------------------------------------------------------
# Configuration de la base de données
#--------------------------------------------------------------------------
spring.h2.console.enabled: true
spring.datasource.username: flowable
spring.datasource.password: flowable
spring.datasource.url: jdbc:h2:mem:flowable


#Role administrateur (au sens keycloak, creable et administrable via sugoi)
#https://gestion-comptes-utilisateurs.recette.insee.fr/
#ce role protege le endpoint starter/healthcheckadmin
fr.insee.sndil.starter.role.administrateur=Admin


#--------------------------------------------------------------------------
# Configuration de springdoc / swagger
#--------------------------------------------------------------------------
#Pour que swagger-ui affiche les endpoint /actuator
springdoc.show-actuator=true
#Pour que l url du swagger soit le / au lieu de swagger-ui/index.html
springdoc.swagger-ui.path=/
springdoc.pathsToMatch=/**
springdoc.swagger-ui.disable-swagger-default-url=true
spring.main.allow-bean-definition-overriding=true
#Client par defaut propose dans la popup de login
springdoc.swagger-ui.oauth.clientId=
#Configuration de la partie springdoc du starter
fr.insee.sndil.starter.springdoc.description=description de l application
fr.insee.sndil.starter.springdoc.issuer-url-authorization=
fr.insee.sndil.starter.springdoc.issuer-url-refresh=
fr.insee.sndil.starter.springdoc.issuer-url-token=
fr.insee.sndil.starter.springdoc.issuer-description=
fr.insee.sndil.starter.springdoc.contact-name=
fr.insee.sndil.starter.springdoc.contact-email=
fr.insee.sndil.starter.springdoc.contact-url=https://www.insee.fr/fr/accueil


#--------------------------------------------------------------------------
# Securite
#--------------------------------------------------------------------------
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=
#Configuration du jeton JWT
#On indique dans quel claim se situent certaines elements car cela peut varier selon la source
#Liste des roles
fr.insee.sndil.starter.security.token.oidc-claim-role=realm_access.roles
fr.insee.sndil.starter.security.token.oidc-claim-username=name

#Liste de chemins (relatifs) sur lesquels aucune securite n est appliquee
#LE / correspond a la redirection du swagger-ui sur le .
fr.insee.sndil.starter.security.whitelist-matchers=/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html,/actuator/**,/error,/


#--------------------------------------------------------------------------
# Actuator
# Il existe plusieurs facon de le configurer
# https://docs.spring.io/spring-boot/docs/3.0.0/reference/htmlsingle/#actuator.endpoints.exposing
#--------------------------------------------------------------------------
management.endpoint.health.show-details=always
#Pour le desactiver globalement et activer endpoint par endpoint
#management.endpoints.enabled-by-default=false
#management.endpoint.info.enabled=true

#--------------------------------------------------------------------------
# Logs
#--------------------------------------------------------------------------
logging.level.root=INFO
logging.level.fr.insee.sndil.starter=INFO
